env:
 - CABALVER=1.20 GHCVER=7.8.4

-notifications:
  - email: false

cache:
 directories:
 - $HOME/.ghc
 - $HOME/.cabal

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install happy-1.19.3
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - wget http://www.stackage.org/lts/1.0/cabal.config
 - travis_retry cabal update
 - cabal-1.20 install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls

script:
 # -v2 provides useful information for debugging
 - cabal-1.20 configure --enable-tests --enable-benchmarks -v2

 # this builds all libraries and executables
 # (including tests/benchmarks)
 - cabal-1.20 build

 - cabal-1.20 test
 - cabal-1.20 check

 # tests that a source-distribution can be generated
 - cabal-1.20 sdist